version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitFeatureProject
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852/TestGitFeatureProject
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.testgitfeature.integrations:testf
  packages:
  - name: TestGitFeatureProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1102
